sudo: required

language: go
go:
  - "1.9.x"

go_import_path: github.com/fmitra/dennis-bot

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop

script:
  - make develop
  - make dev_dependencies
  - docker-compose up -d
  - make test_and_lint
