sudo: required

language: go
go:
  - "1.9.x"

go_import_path: github.com/fmitra/dennis-bot

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop

jobs:
  include:
    - stage: test
      script:
        - make develop
        - make dev_dependencies
        - docker-compose up -d
        - make test_and_lint
    - stage: build
      if: tag =~ ^v
      script:
        - export REPO=fmitra/dennis-bot
        - docker login --username $DOCKER_USER --password-stdin $DOCKER_PASS
        - docker build . -f Dockerfile -t $REPO
        - docker tag $REPO $REPO:$TRAVIS_BUILD_NUMBER
        - docker push $REPO
