sudo: required

language: go
go:
  - "1.10.3"

go_import_path: github.com/fmitra/dennis-bot

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop

jobs:
  include:
    - stage: test
      script:
        - make develop
        - make dev_dependencies
        - docker-compose up -d
        - make test_and_lint
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: build
      if: tag =~ ^v
      script:
        - export REPO=fmitra/dennis-bot
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker build . -f Dockerfile -t $REPO
        - docker tag $REPO $REPO:$TRAVIS_TAG
        - docker push $REPO
