version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dennis
      - POSTGRES_PASSWORD=dennis
      - POSTGRES_DB=dennis
    restart: unless-stopped
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass dennis
    restart: unless-stopped
